### PR TITLE
Fix Issue #10

### PR DESCRIPTION
**Pull request by pvanhese**
Fix for issue #10. Use searchWiki(sarOp) to find all pages possibly containing links to the old wiki word (as before), but use the AST of resulting pages to reliably replace links.

### CODE REVIEW

**Comment by butscher** [comment]
Unfortunately your pull request is also unreliable because there can be:

- Subpages, so e.g. renaming "Foo" to "Bar" also requires to rename "//Foo/SubPage" to "//Bar/SubPage"
- Scripts containing page names
- Attributes and other insertions as "page" to process page names (new insertions can be added by plugins), e.g. the attributes "import_scripts" and "template" expect wiki pages

**Comment by pvanhese** [comment]
Thanks for your feedback. It helped me to improve my proposed fix.

Next to the problems you pointed out, there were some other problems:
* Renaming a camelcase wiki word to a non-camelcase wiki word, and visa versa:
    * renaming *WikiWord* to *wikiword* requires changing the text `WikiWord` to `[wikiword]`, i.e., brackets are needed to make a link (and the brackets were missing);
    * and visa versa, renaming *wikiword* to *WikiWord* means changing the text `[wikiword]` to `WikiWord`, i.e., brackets are not needed (and the brackets were still in the text).
* Using `searchWiki(sarOp)` to find all pages containing links to the old wiki word is not very reliable, as it only looks for a literal text match with the old wiki word: it can miss links to subpages (false negatives), and it can result in many pages containing a match that is not a link (false positives). 

To tackle these issues, I made the following changes:
1. Instead of using `searchWiki(sarOp)` to find pages that need to be updated:
    * use `getParentRelationships(wikiWord)` to get a list of all pages linking to the old wiki word (i.e., its parents) (WikidPad already tracks these);
    * add `AttributeHandling.ATTRIBUTES_WITH_WIKIWORD_VALUES`, a list that holds attribute keys for those attributes that have wiki word values, i.e., `template`, `parent`, `import_scripts`. Use `getAttributeTriples` to find those attributes (WikidPad already caches attributes);
    * do a text search to find page insertions (a text search is still required to find insertions as, to my knowledge, WikidPad does not cache these).

2. Use the AST and `langHelper.createLinkFromWikiWord`: use the AST to find wiki word links, and use `langHelper.createLinkFromWikiWord` to turn the new wiki word into a link that can be used as the new text. This solves the problem of handling camelcase vs. non-camelcase wiki words, as `langHelper.createLinkFromWikiWord` adds brackets (if and only if) where needed. It also solves handling subpage links, as `langHelper.createLinkFromWikiWord` resolves these. And it leaves it to the parser to decide what (the syntax of) a link is, so it probably also works for custom made wiki languages.


This means that now:

* Renaming subpages works, e.g., renaming *Foo* to *Bar* also renames *Foo/SubPage* to *Bar/SubPage* and updates all links to these.

* It can not handle page names used in scripts (see limitations below).

* It can handle page insertions, i.e., `[:page: ..]`.

* It can handle attributes with wiki word values, i.e., `[template: ..]`, `[import_scripts: ..]`, `[parent: ..]`.


Limitations:

* It can not rename page names used in scripts. Scripts are simply too dynamic to allow a static replacement, e.g., a script could reference *Foo* via `getWikiPage(u'F' + u'o' + u'o')` (in that case a simple text search & replace operation will not save you either). If it is important to catch this, you could monitor page requests at run time, and notify the user if WikidPad tries to open a page with an old name.

* If a plugin defines a new attribute that has a wiki word value, its key needs to be added to `AttributeHandling.ATTRIBUTES_WITH_WIKIWORD_VALUES`.

* Likewise, if a plugin defines a new insertion which has a wiki word value, the text search for insertions needs to include this new insertion.

* When modifying text, we need to check every attribute and insertion because its value needs to be resolved first before we can check whether it refers to the old wiki word (because of subpages a literal match is not possible). This can be slow if the wiki contains many attributes with wiki word values and insertions. If needed, we could speed this up by caching the _resolved_ attribute and insertion values, so that a literal search with the old wiki word is possible.


I tested (among others) the following examples:

- [x] given *//Foo* and *//Foo/SubPage*, rename *Foo* to *Bar* : changes *//Foo/SubPage* to *//Bar/SubPage*

- [x] given *Foo* and *Foo/Foo*, rename *Foo* to *Bar* : changes *Foo* to *Bar* and *Foo/Foo* to *Bar/Foo*

- [x] given *//Foo/Foo*, rename *Foo/Foo* to *Foo/Bar* works

- [x] given *main1* with link to *main1/sub1* with text `[alias:alias1]`, rename *main1* to *main1renamed* : links are updated, *main1renamed/alias1* works

- [x] given *Spam* with links to *Foo* and *Foo/SubPage*, and *Foo* with a link to *Foo/SubPage*, rename *Foo* to *Bar* : links are updated, *Foo* is renamed to *Bar*, *Foo/SubPage* is renamed to *Bar/SubPage*

- [x] given link to *OfLgii* (camelcase), rename to *1OfLgii* (non-camelcase) : changes link to `[1OfLgii]` (brackets are added)

- [x] given link `[Python]` (non-camelcase), rename *Python* to *PythonFOSDEM* (camelcase) : changes link to `PythonFOSDEM` (no brackets)

- [x] given `[template: Foo]`, rename *Foo* to *Bar* : changes attribute to `[tempate: Bar]`

- [x] given `[import_scripts: Foo]`, rename *Foo* to *Bar* : changes attribute to `[import_scripts: Bar]`

- [x] given `[:page: wikiWord]`, rename *wikiWord* to *ww* : changes insertion to `[:page: ww]`

- [x] link `[.]` (self link) still works after renaming

- [x] link `[..]` still works after renaming

- [x] given *Python* and link `[April Python Meeting]`, rename *Python* to *Python35* : link unchanged

- [x] given *in* and text `Python: programming the way Guido indented it`, rename *in* to *Inbox* : text unchanged (`indented` is not replaced with `Inboxdented`)


Hopeful conclusion: the current search & replace operation used to modify text when renaming wiki words is unreliable and dangerous to use (it easily breaks links and distorts text). In practice you need to do a manually search & replace and carefully check all changes, which is cumbersome and error-prone. This fix allows a reliable replacement of all static references to the old wiki word (wiki links, attribute values and page insertions) with the new wiki word. Page names used in scripts still need to be renamed manually.


Next actions:

* The code still contains a number of print statements from testing the code; they can be removed.

* How can I automate testing? At the moment I try different examples by hand, but this quickly becomes tiresome. Does WikidPad have a test suite?

**Comment by butscher** [comment]
> Renaming a camelcase wiki word to a non-camelcase wiki word, and visa versa

This unfortunately leads to a bigger problem. The code you added to handle this only works for the default wiki language. WikidPad ships with a simplified MediaWiki language as well (where only wiki words in [[double brackets]] are allowed) and supports other custom languages.

A simple example is http://trac.wikidpad2.webfactional.com/wiki/OverlayParser which shows how to create a modified language where bracketed wiki words become duble bracketed, too.

> a text search is still required to find insertions as, to my knowledge, WikidPad does not cache these

You are right. I never saw the necessity.

> How can I automate testing? At the moment I try different examples by hand, but this quickly becomes tiresome. Does WikidPad have a test suite?

WikidPad currently hasn't a test suite or support for that.

I think that it is not possible to create a perfect renaming functionality without a lot of work and maybe changes to the plugin interfaces (actually we would need a syntax generator alongside each parser to be sure that the changes produce the desired content).

My idea would be to replace in the `renameWikiWord(self, wikiWord, toWikiWord, modifyText)` function(s) the boolean `modifyText` parameter by a string to select a method between "off", "simple" (old method) and "advanced" (your method). The GUI would then provide a way to select the desired method.

Later it would be possible to add more methods, e.g. a method provided by a parser plugin which is specifically crafted for this parser.

**Comment by pvanhese** [comment]
Thank you for your feedback. I looked into both the MediaWiki and Overlay languages and adapted my method so that it can now also deal with these languages.

To that end, I generalized the method and wrote some additional code, most importantly a text generator for each language (which takes the AST as input and outputs text, formatted according to the syntax of the particular language). I also needed to adapted each parser to add the attribute `linkPath` to each `wikiWord` node so that the text generator can correctly format the links (`linkPath` is a `WikiLinkPath` object that represents the target of the wiki link, see below).

In fact, I believe that the approach is now general enough to work with other custom languages as well, although some extra code will have to be written for each of these (but starting from `WikidPadParser` as an example this should prove to be not too difficult).

A high level overview of the approach is as follows: when renaming wiki words, update the text of affected pages (i.e., pages which refer to old page names) in three steps:

1. Use the language parser to get the AST of the text.
2. Transform the AST by updating the values of the `wikiWord`, `attribute` and `insertion` nodes to  the new page names.
3. Use the text generator of the particular language with the updated AST as input, to get the updated text.

The sections below list in more detail the changes I made and the requirements to make this work for other (custom) languages.


## Changes

### Text generator

I added a text generator to `WikidPadParser` for the default wiki language, and made it work also with the MediaWiki and Overlay language.

The text generator takes the AST as input, and returns the text formatted according to the syntax of the wiki language. The returned text is like `ast.getString()`, but the crucial difference here is that the text generator (in general) only relies on the node values. For instance, for the node `attribute`, it uses the keys and values stored in `node.attrs` to generate the text, not the `text` attribute of its children (like `ast.getString()` does).

Because the output of the text generator only depends on the node values, transforming the AST to get an updated text is both simple and elegant (see the function `WikiDataManager._updateWikiWordReferences`). For instance, when updating wiki word links, it is not necessary anymore to update the text nodes (which was tricky because the exact text depends on the syntax of the particular language, e.g., double vs. single square brackets, and the problems with links for camelcase vs. non-camelcase wiki words). Transforming the AST now means only updating the values of the nodes and the text generator handles the details of how the text should be formatted. In the case of updating wiki word reference, we only need to update the `wikiWord`, `attribute` and `insertion` nodes.

The text generator works by traversing the AST. For each node it calls the visitor method for that node to format the text based on the node value(s) (there is one visitor method per node type). For now, only visitor methods for the nodes `wikiWord`, `attribute` and `insertion` are implemented, and it falls back on `getString` for the other nodes. These visitor methods, however, are the only ones needed to reliably update wiki word references.

Because we only need a partial implementation of the text generator to make updating the text work reliably (instead of a full implementation; we do not need visitor methods for all nodes, we can fall back on `getString` for nodes other than `wikiWord`, `attribute` and `insertion`), it is feasible to implement it also or other custom languages (start from the example in `WikidPadParser`).

The text generator in the `MediaWikiParser` is almost a verbatim copy of the one in `WikidPadParser`, except for some small differences due to the use of double square brackets instead of single square brackets, and not using camelcase wiki words.

To make it work for `OverlayParser` I only had to add a few expressions to its `PAYLOAD`  to handle the syntax differences with the standard wiki language (again double square brackets vs. single square brackets).


### The linkPath attribute in wikiWord nodes

I adapted each parser to add the attribute `linkPath` to each `wikiWord` node of the AST. This attribute is a `WikiLinkPath` object which represents the wiki link in the text.

When updating references in the text, you need to keep absolute links absolute and relative links relative (I did not do that before). However, the `wikiWord` node stores in its attribute `wikiWord` only the page name (i.e., the resolved link). Based on this value only, the text generator can not know whether to generate an absolute or a relative link. Therefore, I added the attribute `linkPath` which is the `WikiLinkPath` of the target wiki word, so that the text generator can generate the correct link (absolute or relative) on the base page with `.getLinkCore()`.

The `linkPath` attribute is added in the parse actions for the wiki words, in both `WikidPadParser` and MediaParser. For the OverlayParser I did not have to make any changes, because it executes the `WikidPadParser`.


### WikiLinkPath

Handling wiki links (both in `WikiDataManager._updateWikiWordReferences` and in the text generator) hinges on `WikiLinkPath`. This class represents wiki links and handles subpages. To better understand its internals and to make sure it works correctly in all cases, I added a number of tests (see below). I made some changes to `WikiLinkPath` and fixed some corner cases so that resolving and creating wiki links works correctly (see tests).


### PersonalWikiFrame.renameWikiWord

The `modifyText` parameter now takes a `ModifyText` enum. The possible values are `ModifyText.off`, `ModifyText.advanced` (new method) and `ModifyText.simple` (old method).



### WikiDataManager.renameWikiWords

The rename function now takes a rename dictionary as input (instead of a rename sequence) which maps the old page names to the new page names. With the previous approach, when renaming subpages, each page could be visited many times to update its text, once for every element of the rename sequence. With the rename dictionary, each page is visited only once, and all links to all changed page names are updated in one go.

The function `renameWikiWord` (without s) is simplified to only do the renaming of pages. Finding pages that need their text updated is done in `_findPagesThatReferenceWord`. Updating the text is done in `_updateWikiWordReferences` (using the three steps outlined above and handling all required updates in one go). `renameWikiWords` ties everything together.


## Requirements

To make renaming work for other languages (and/or custom attributes), this is required (see `WikidPadParser` and `MediaWikiParser`):

* the parser should add a `linkPath` attribute to `wikiWord` nodes. This attribute holds a `WikiLinkPath` of the target page so that correct links can be generated in the text generator;

* `langHelper` should provide the following attributes and methods: `WikiLinkPath` (to represent wiki links), `resolveWikiWordLink` and `createWikiLinkPathFromPathName` to, resp., resolve and create wiki links (used when transforming the AST), and `generate_text` (the interface to the text generator);

* `ATTRIBUTES_WITH_WIKIWORD_VALUES` (list of attributes that might refer to page names) needs to be up-to-date (add custom attributes when needed).



## Test suite

I added a test suite for the new functionality. The tests are located in the subdirectory `tests/`. Run with [pytest](https://docs.pytest.org/) from the main directory: `...\WikidPad> pytest`.

#### test_WikidPadParser

* Do basic tests of the parser (mostly to check my helper functions)
* Test `WikiLinkPath`
* Test creating and resolving wiki links
* Test the text generator. To test the text generator (besides some simple tests I included), I run the text generator over the *complete* WikidPadHelp wiki: parse each page of the wiki, generate text based on the page's AST using the text generator, and then check if the generated text matches the original text (it should).

  At first, I did find some differences, but it turned out that these literal differences are in fact no errors, but small differences in syntax with the same semantics, e.g., `[key:  value  ]` in the original text was formatted as `[key: value]` in the generated text (note no extra spaces) (and many more cases like these). I recorded these differences in an annotation file so that the test can ignore these (i.e., not report them as errors). The text generator has no errors for this wiki.

#### test_OverLayParser

Basic tests of the parser.


#### test_MediaWikiParser

Basic tests of the parser.


#### test_WikiDataManager

Test `renameWikiWords(renameDict, modifyText)` with the methods `advanced` and `simple`. To test `renameWikiWords`, I run it on a number of test wikis and compared the obtained results with the expected results.

The contents of all test wikis is stored in the files `tests/test_wikis_*_before_rename.txt` (content before renaming + renaming sequence tested per wiki) and `tests/test_wikis_*_after_rename.txt` (the expected content after renaming).

The test wikis include all the examples from my previous post.

The method `advanced` passes all tests. The method `simple` fails for many test wikis (as expected).


## Next actions


* Adapt parsers of and/or add (partial) text generators for other custom languages, so that renaming also works with these languages? Is there a list of custom parser/languages for WikidPad to check?

* Improve `_findPagesThatReferenceWord` by caching values for attributes and page insertions?

  We could speed up the function `_findPagesThatReferenceWord`, if needed, by caching values for attributes (store the page name, i.e., the resolved wiki link so that we can query to get only the pages the reference old page names, instead of needed to try them all), and page insertion (idem, store the resolved value).

  Note that doing so would improve speed, but updating references as it is implemented now works correct regardless (it might simply check too many pages because `_findPagesThatReferenceWord` returns unnecessary candidate pages).

* Update the plugin API for custom languages? For now, the text generator is available through the language helper.

**Comment by butscher** [comment]
Finally I have now merged your changes into the master branch (after some adjustments) and made it available in a new version of WikidPad. Thank you.

**Comment by pvanhese** [comment]
You're welcome, glad I could help. 

I updated the tests (see #19) to reflect the change you made to `WikiDataManager.renameWikiWords`, i.e., renaming the pages in the database after modifying the links.

Unfortunately, this change (renaming pages after updating text) causes the tests to fail.

Looking at the errors, you'll see that the problem lies with relative links and self links. For instance, for test wiki nr. 22, the test page `Foo` with link `[/SubPage]` should remain `[/SubPage]` after renaming `Foo` to `Bar`, but now instead becomes `[Bar/SubPage]`, because if you rename the page only after modifying the links, at the time you update the link, the page will still be named `Foo` and thus the link the subpage of `Bar` will be `[Bar/SubPage]`. Similarly, self links will be replace with absolute links to the old page name, instead of `[.]`.

Is there a reason why you would like to rename the pages after modifying the links, instead of first renaming the pages and then modifying the links (which feels more natural to me)?

If so, `WikiDataManager._updateWikiWordReferences` will have to be changed.

If not, I would recommend to change `WikiDataManager.renameWikiWords` again so that the text is updated only after first renaming all pages.

**Comment by butscher** [comment]
> Is there a reason why you would like to rename the pages after modifying the links, instead of first renaming the pages and then modifying the links (which feels more natural to me)?

To be honest I can't remember why I did this. My own testing doesn't show a problem when using your recommended order of execution so I changed it back (c0997839935c202abb24b012c7c7ef99919b4cd4).

**Comment by butscher** [comment]
**1**

> For instance, the heading examples (= Heading 1 =, == Heading 2 ==, …) are not recognized by WikidPadParser as headings, because they are not valid WikidPad syntax

It is a general problem in some cases if the help wiki should be written so that it looks correctly in edit mode or preview mode. Here I decided it should be readable in edit mode but it may be written in a better way using a pre-block.

> This is ok for valid input text, but for invalid text input (invalid syntax) the output of the parser is not well defined.

Actually it is well defined. Every possible input to the parser is valid. Particular parts of the input are either correctly written formatting (wiki words, tables, ...) or just plain text.

> At best, you can read it as a link surrounded by square brackets, but in valid WikidPad syntax this should be written as \[[TextFormatting]\]s, i.e., you need to escape the brackets to make the parsing unambiguous.

`[[Foo]]` is unambiguous. When the parser looks at the first '`[`' it tests (among other things) for a wiki word but the second '`[`' can't be in a wiki word. Other possibilities (attribute, insertion, ...) are also ruled out so the parser concludes that the first '`[`' must be plain text and continues with the second '`[`'. Technically, most of the testing is done by large regular expressions to make it fast.

The formatter only works correctly if for any input the combination parser+formatter produces output which is semantically equivalent to the input. This wasn't the case for `[[Foo]]`.

**2**

> An important concern when renaming wiki words was to make sure that links are formatted correctly. When renaming a camelcase wiki word to a non-camelcase wiki word (and visa versa), brackets need to be handled correctly. For instance, see renaming Python to PythonFOSDEM in the discussion above, and many more examples, both in the discussion and in the test wikis (before the change); the change you propose breaks this.

I don't know of a case where converting a bracketless camelcase wiki word to a bracketed word (camelcase or not) breaks or changes the semantic meaning. Did I overlook something?

So I thought that it would be safest to create a bracketed word if there is any possibility that the bracketless word could break.

> > My own testing doesn't show a problem when using your recommended order of execution
> 
> Is this with the tests in \tests, or do you have an additional tests?

My own testing, but this only meant some random manual renaming.

**Pull request merged**
